### ISSUE TITLE
请问头文件是怎么筛出来的？

### ISSUE THREAD

**Issue by palanceli** [dodola/BinderDebug#1]
非常棒的指南！
在“编译Demo例子”一节中，那些头文件包含的内容非常多，请问是怎么筛出来的呢？
如果要调试系统其它的so文件，怎么知道都依赖了哪些头文件呢？

**Comment by dodola** [comment]
@palanceli 基本上就是看系统源码所使用的头文件，然后一个一个筛出来，从系统源码中分析出来的
